# Generated by Django 2.0.7 on 2018-09-01 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20180901_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifiaction',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
        migrations.AlterField(
            model_name='notifiaction',
            name='notifiaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('commnent', 'Comment'), ('follow', 'Follow')], max_length=20),
        ),
    ]
