# Generated by Django 2.0.7 on 2018-09-01 11:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_auto_20180901_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifiaction',
            new_name='Notification',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notifiaction_type',
            new_name='notification_type',
        ),
    ]
