# Generated by Django 2.0.7 on 2018-08-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180827_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('not-specified', 'Not-specified'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
