# Generated by Django 2.0.7 on 2018-09-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180901_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not-specified'), ('female', 'Female'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
